# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import storage_server_pb2 as storage__server__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in storage_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SqliteProxyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSession = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/OpenSession',
                request_serializer=storage__server__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=storage__server__pb2.OpenSessionResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/CloseSession',
                request_serializer=storage__server__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=storage__server__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/Execute',
                request_serializer=storage__server__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=storage__server__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.ExecuteMany = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/ExecuteMany',
                request_serializer=storage__server__pb2.ExecuteManyRequest.SerializeToString,
                response_deserializer=storage__server__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.ExecuteBatch = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/ExecuteBatch',
                request_serializer=storage__server__pb2.ExecuteBatchRequest.SerializeToString,
                response_deserializer=storage__server__pb2.ExecuteBatchResponse.FromString,
                _registered_method=True)
        self.ExecuteScript = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/ExecuteScript',
                request_serializer=storage__server__pb2.ExecuteScriptRequest.SerializeToString,
                response_deserializer=storage__server__pb2.ExecuteScriptResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/ReadFile',
                request_serializer=storage__server__pb2.FileReadRequest.SerializeToString,
                response_deserializer=storage__server__pb2.FileReadResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.stream_unary(
                '/storage_server.v1.SqliteProxy/WriteFile',
                request_serializer=storage__server__pb2.FileWriteChunk.SerializeToString,
                response_deserializer=storage__server__pb2.FileWriteResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/ListFiles',
                request_serializer=storage__server__pb2.FileListRequest.SerializeToString,
                response_deserializer=storage__server__pb2.FileListResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/DeleteFile',
                request_serializer=storage__server__pb2.FileDeleteRequest.SerializeToString,
                response_deserializer=storage__server__pb2.FileDeleteResponse.FromString,
                _registered_method=True)
        self.ProvisionUser = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/ProvisionUser',
                request_serializer=storage__server__pb2.ProvisionUserRequest.SerializeToString,
                response_deserializer=storage__server__pb2.ProvisionUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/DeleteUser',
                request_serializer=storage__server__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=storage__server__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.AdminHealth = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/AdminHealth',
                request_serializer=storage__server__pb2.AdminHealthRequest.SerializeToString,
                response_deserializer=storage__server__pb2.AdminHealthResponse.FromString,
                _registered_method=True)
        self.BackupDatabase = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/BackupDatabase',
                request_serializer=storage__server__pb2.BackupDatabaseRequest.SerializeToString,
                response_deserializer=storage__server__pb2.BackupDatabaseResponse.FromString,
                _registered_method=True)
        self.ExportUserBackup = channel.unary_stream(
                '/storage_server.v1.SqliteProxy/ExportUserBackup',
                request_serializer=storage__server__pb2.ExportUserBackupRequest.SerializeToString,
                response_deserializer=storage__server__pb2.ExportUserBackupChunk.FromString,
                _registered_method=True)
        self.ExportSyncSnapshot = channel.unary_stream(
                '/storage_server.v1.SqliteProxy/ExportSyncSnapshot',
                request_serializer=storage__server__pb2.ExportSyncSnapshotRequest.SerializeToString,
                response_deserializer=storage__server__pb2.ExportSyncSnapshotChunk.FromString,
                _registered_method=True)
        self.RestoreUserBackup = channel.stream_unary(
                '/storage_server.v1.SqliteProxy/RestoreUserBackup',
                request_serializer=storage__server__pb2.RestoreUserBackupChunk.SerializeToString,
                response_deserializer=storage__server__pb2.RestoreUserBackupResponse.FromString,
                _registered_method=True)
        self.FindPlaidItemOwner = channel.unary_unary(
                '/storage_server.v1.SqliteProxy/FindPlaidItemOwner',
                request_serializer=storage__server__pb2.FindPlaidItemOwnerRequest.SerializeToString,
                response_deserializer=storage__server__pb2.FindPlaidItemOwnerResponse.FromString,
                _registered_method=True)


class SqliteProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvisionUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackupDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportUserBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportSyncSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreUserBackup(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPlaidItemOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SqliteProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=storage__server__pb2.OpenSessionRequest.FromString,
                    response_serializer=storage__server__pb2.OpenSessionResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=storage__server__pb2.CloseSessionRequest.FromString,
                    response_serializer=storage__server__pb2.CloseSessionResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=storage__server__pb2.ExecuteRequest.FromString,
                    response_serializer=storage__server__pb2.ExecuteResponse.SerializeToString,
            ),
            'ExecuteMany': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteMany,
                    request_deserializer=storage__server__pb2.ExecuteManyRequest.FromString,
                    response_serializer=storage__server__pb2.ExecuteResponse.SerializeToString,
            ),
            'ExecuteBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteBatch,
                    request_deserializer=storage__server__pb2.ExecuteBatchRequest.FromString,
                    response_serializer=storage__server__pb2.ExecuteBatchResponse.SerializeToString,
            ),
            'ExecuteScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScript,
                    request_deserializer=storage__server__pb2.ExecuteScriptRequest.FromString,
                    response_serializer=storage__server__pb2.ExecuteScriptResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=storage__server__pb2.FileReadRequest.FromString,
                    response_serializer=storage__server__pb2.FileReadResponse.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=storage__server__pb2.FileWriteChunk.FromString,
                    response_serializer=storage__server__pb2.FileWriteResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=storage__server__pb2.FileListRequest.FromString,
                    response_serializer=storage__server__pb2.FileListResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=storage__server__pb2.FileDeleteRequest.FromString,
                    response_serializer=storage__server__pb2.FileDeleteResponse.SerializeToString,
            ),
            'ProvisionUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvisionUser,
                    request_deserializer=storage__server__pb2.ProvisionUserRequest.FromString,
                    response_serializer=storage__server__pb2.ProvisionUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=storage__server__pb2.DeleteUserRequest.FromString,
                    response_serializer=storage__server__pb2.DeleteUserResponse.SerializeToString,
            ),
            'AdminHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminHealth,
                    request_deserializer=storage__server__pb2.AdminHealthRequest.FromString,
                    response_serializer=storage__server__pb2.AdminHealthResponse.SerializeToString,
            ),
            'BackupDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.BackupDatabase,
                    request_deserializer=storage__server__pb2.BackupDatabaseRequest.FromString,
                    response_serializer=storage__server__pb2.BackupDatabaseResponse.SerializeToString,
            ),
            'ExportUserBackup': grpc.unary_stream_rpc_method_handler(
                    servicer.ExportUserBackup,
                    request_deserializer=storage__server__pb2.ExportUserBackupRequest.FromString,
                    response_serializer=storage__server__pb2.ExportUserBackupChunk.SerializeToString,
            ),
            'ExportSyncSnapshot': grpc.unary_stream_rpc_method_handler(
                    servicer.ExportSyncSnapshot,
                    request_deserializer=storage__server__pb2.ExportSyncSnapshotRequest.FromString,
                    response_serializer=storage__server__pb2.ExportSyncSnapshotChunk.SerializeToString,
            ),
            'RestoreUserBackup': grpc.stream_unary_rpc_method_handler(
                    servicer.RestoreUserBackup,
                    request_deserializer=storage__server__pb2.RestoreUserBackupChunk.FromString,
                    response_serializer=storage__server__pb2.RestoreUserBackupResponse.SerializeToString,
            ),
            'FindPlaidItemOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPlaidItemOwner,
                    request_deserializer=storage__server__pb2.FindPlaidItemOwnerRequest.FromString,
                    response_serializer=storage__server__pb2.FindPlaidItemOwnerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage_server.v1.SqliteProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage_server.v1.SqliteProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SqliteProxy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/OpenSession',
            storage__server__pb2.OpenSessionRequest.SerializeToString,
            storage__server__pb2.OpenSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/CloseSession',
            storage__server__pb2.CloseSessionRequest.SerializeToString,
            storage__server__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/Execute',
            storage__server__pb2.ExecuteRequest.SerializeToString,
            storage__server__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/ExecuteMany',
            storage__server__pb2.ExecuteManyRequest.SerializeToString,
            storage__server__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/ExecuteBatch',
            storage__server__pb2.ExecuteBatchRequest.SerializeToString,
            storage__server__pb2.ExecuteBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/ExecuteScript',
            storage__server__pb2.ExecuteScriptRequest.SerializeToString,
            storage__server__pb2.ExecuteScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/ReadFile',
            storage__server__pb2.FileReadRequest.SerializeToString,
            storage__server__pb2.FileReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/storage_server.v1.SqliteProxy/WriteFile',
            storage__server__pb2.FileWriteChunk.SerializeToString,
            storage__server__pb2.FileWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/ListFiles',
            storage__server__pb2.FileListRequest.SerializeToString,
            storage__server__pb2.FileListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/DeleteFile',
            storage__server__pb2.FileDeleteRequest.SerializeToString,
            storage__server__pb2.FileDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvisionUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/ProvisionUser',
            storage__server__pb2.ProvisionUserRequest.SerializeToString,
            storage__server__pb2.ProvisionUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/DeleteUser',
            storage__server__pb2.DeleteUserRequest.SerializeToString,
            storage__server__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/AdminHealth',
            storage__server__pb2.AdminHealthRequest.SerializeToString,
            storage__server__pb2.AdminHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackupDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/BackupDatabase',
            storage__server__pb2.BackupDatabaseRequest.SerializeToString,
            storage__server__pb2.BackupDatabaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportUserBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/storage_server.v1.SqliteProxy/ExportUserBackup',
            storage__server__pb2.ExportUserBackupRequest.SerializeToString,
            storage__server__pb2.ExportUserBackupChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportSyncSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/storage_server.v1.SqliteProxy/ExportSyncSnapshot',
            storage__server__pb2.ExportSyncSnapshotRequest.SerializeToString,
            storage__server__pb2.ExportSyncSnapshotChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreUserBackup(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/storage_server.v1.SqliteProxy/RestoreUserBackup',
            storage__server__pb2.RestoreUserBackupChunk.SerializeToString,
            storage__server__pb2.RestoreUserBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPlaidItemOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage_server.v1.SqliteProxy/FindPlaidItemOwner',
            storage__server__pb2.FindPlaidItemOwnerRequest.SerializeToString,
            storage__server__pb2.FindPlaidItemOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
